### ISSUE TITLE
Turn on vue production mode

### ISSUE THREAD

**Issue by petehalverson** [gvalkov/tailon#10]
`3rdparty.js` currently bundles vue/dist/vue.js (which is used for development)

Using the minified version in the [`EXTERNAL_JS`](https://github.com/gvalkov/tailon/blob/master/frontend/Makefile#L9) list will resolve the issue.

https://vuejs.org/v2/guide/deployment.html#Without-Build-Tools

**Comment by petehalverson** [comment]
Also noticed a number of console.log() calls that should probably be turned off in production.

Would you consider switching to a webpack build process for the frontend?

**Comment by gvalkov** [comment]
Thanks for the tip and apologies for the long wait. I've done as you suggested in 25e9227cc91a3865acfa2ed2d2e4ac5b05824eca and 89380bfb1227e205ee77cd12b69da3e475a2522e. 

I know it may be limiting, but I prefer if the make-build stayed. I'm simply not that familiar with webpack.

**Comment by petehalverson** [comment]
Awesome. Thanks!
