### ISSUE TITLE
How to load a toml file ?

### ISSUE THREAD

**Issue by blackwindrunner** [gvalkov/tailon#3]
I write a config.toml that contains as following code:

  title = "Tailon file viewer"
  relative-root = "/"
  listen-addr = ":8081"
  allow-download = true
  allow-commands = ["tail", "grep", "sed", "awk"]
  [commands]
    [commands.tail]
    action = ["tail", "-n", "$lines", "-F", "$path"]
    [commands.grep]
    stdin = "tail"
    action = ["grep", "--text", "--line-buffered", "--color=never", "-e", "$script"]
    default = ".*"
    [commands.sed]
    stdin = "tail"
    action = ["sed", "-u", "-e", "$script"]
    default = "s/.*/&/"
    [commands.awk]
    stdin = "tail"
    action = ["awk", "--sandbox", "$script"]
    default = "{print $0; fflush()}"

I run the commond "tailon  -c config.toml", tip "No files specified on command-line or in config file".

**Comment by gvalkov** [comment]
Hi. This should now work (fffdf3fe57cef675341c44cbee946d8a81c3ff8a). However, at the moment it's not possible to mix configuration from the config file with command-line options.
