### ISSUE TITLE
Binding to multiple IP addresses

### ISSUE THREAD

**Issue by TheColonel2688** [gvalkov/tailon#4]
It is possible to have Tailon bind to 2 or more IP addresses? I have a machine that has 2 and I would like to be able to access it with both.

If so what is the syntax?

**Comment by DmitriyLyalyuev** [comment]
Regarding help `tailon --help` you can start it on all interfaces. Something like:
tailon --bind 0.0.0.0:<portnumber>

**Comment by gvalkov** [comment]
Hi @TheColonel2688 - since f2b575aae4b7aacc59d0380cf7af709d50d7465d it's possible to do this. Use `tailon -b localhost:8080,10.0.0.1:8081 ...` on the cli or `bind-addr: ["localhost:8080","10.0.0.1:8081"]` in the config file.
